/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algo;

import org.junit.Test;
import static org.junit.Assert.*;

public class CommonTest {
    @Test public void testSomeLibraryMethod() {
        Common classUnderTest = Common.getInstance();
        assertTrue("someLibraryMethod should return 'true'", Common.getInstance());
    }
}
